// GENERATED by tools/cencgen from proto/hyperdht.cenc — do not edit by hand.
module libp2p.wire.hyperdht;

import libp2p.wire.cenc : State, Uint, Uint16, Fixed, Buffer, ArrayOf, Ipv4Address, Address;

enum HsCommand : uint
{
	PEER_HANDSHAKE = 0,
	PEER_HOLEPUNCH = 1,
	FIND_PEER = 2,
	LOOKUP = 3,
	ANNOUNCE = 4,
	UNANNOUNCE = 5,
	MUTABLE_PUT = 6,
	MUTABLE_GET = 7,
	IMMUTABLE_PUT = 8,
	IMMUTABLE_GET = 9
}

enum RpcCommand : uint
{
	PING = 0,
	PING_NAT = 1,
	FIND_NODE = 2,
	DOWN_HINT = 3,
	DELAYED_PING = 4
}

struct PeerRecord
{
	ubyte[32] publicKey;
	Address[] relayAddresses;

	/// The flags varint (OR of the @bits present); 0 when the message has none.
	ulong flags_() const @safe pure nothrow
	{
		return 0UL;
	}

	/// Size pass: advance `s.end` by this message's wire size (inline, no framing).
	void preencode(ref State s) const
	{
		Fixed!32.preencode(s, publicKey[]);
		ArrayOf!Ipv4Address.preencode(s, relayAddresses);
	}

	/// Fill pass: write this message at `s.start` (after preencode + allocate).
	void encodeInto(ref State s) const
	{
		Fixed!32.encode(s, publicKey[]);
		ArrayOf!Ipv4Address.encode(s, relayAddresses);
	}

	/// Two-pass encode: size, allocate once, fill — the reference's c.encode.
	ubyte[] encode() const
	{
		State s;
		preencode(s);
		s.buffer = new ubyte[](s.end);
		encodeInto(s);
		return s.buffer;
	}

	/// Read this message at `s.start` (inline).
	static PeerRecord decodeFrom(ref State s)
	{
		PeerRecord m;
		m.publicKey[] = Fixed!32.decode(s)[0 .. 32];
		m.relayAddresses = ArrayOf!Ipv4Address.decode(s);
		return m;
	}

	static PeerRecord decode(ubyte[] buf)
	{
		auto s = State(0, buf.length, buf);
		return decodeFrom(s);
	}
}

struct Announce
{
	bool hasPeer;
	PeerRecord peer;
	bool hasRefresh;
	ubyte[32] refresh;
	bool hasSignature;
	ubyte[64] signature;
	uint bump;

	/// The flags varint (OR of the @bits present); 0 when the message has none.
	ulong flags_() const @safe pure nothrow
	{
		return (hasPeer ? 1UL : 0UL) | (hasRefresh ? 2UL : 0UL) | (hasSignature ? 4UL : 0UL) | (bump != 0 ? 8UL : 0UL);
	}

	/// Size pass: advance `s.end` by this message's wire size (inline, no framing).
	void preencode(ref State s) const
	{
		Uint.preencode(s, flags_);
		if (hasPeer)
			peer.preencode(s);
		if (hasRefresh)
			Fixed!32.preencode(s, refresh[]);
		if (hasSignature)
			Fixed!64.preencode(s, signature[]);
		if (bump != 0)
			Uint.preencode(s, bump);
	}

	/// Fill pass: write this message at `s.start` (after preencode + allocate).
	void encodeInto(ref State s) const
	{
		Uint.encode(s, flags_);
		if (hasPeer)
			peer.encodeInto(s);
		if (hasRefresh)
			Fixed!32.encode(s, refresh[]);
		if (hasSignature)
			Fixed!64.encode(s, signature[]);
		if (bump != 0)
			Uint.encode(s, bump);
	}

	/// Two-pass encode: size, allocate once, fill — the reference's c.encode.
	ubyte[] encode() const
	{
		State s;
		preencode(s);
		s.buffer = new ubyte[](s.end);
		encodeInto(s);
		return s.buffer;
	}

	/// Read this message at `s.start` (inline).
	static Announce decodeFrom(ref State s)
	{
		Announce m;
		immutable flags_ = Uint.decode(s);
		if (flags_ & 1)
		{
			m.peer = PeerRecord.decodeFrom(s);
			m.hasPeer = true;
		}
		if (flags_ & 2)
		{
			m.refresh[] = Fixed!32.decode(s)[0 .. 32];
			m.hasRefresh = true;
		}
		if (flags_ & 4)
		{
			m.signature[] = Fixed!64.decode(s)[0 .. 64];
			m.hasSignature = true;
		}
		if (flags_ & 8)
		{
			m.bump = cast(uint) Uint.decode(s);
		}
		return m;
	}

	static Announce decode(ubyte[] buf)
	{
		auto s = State(0, buf.length, buf);
		return decodeFrom(s);
	}
}

struct LookupReply
{
	PeerRecord[] peers;
	uint bump;

	/// The flags varint (OR of the @bits present); 0 when the message has none.
	ulong flags_() const @safe pure nothrow
	{
		return 0UL;
	}

	/// Size pass: advance `s.end` by this message's wire size (inline, no framing).
	void preencode(ref State s) const
	{
		Uint.preencode(s, peers.length);
			foreach (ref x; peers)
				x.preencode(s);
		if (bump != 0)
			Uint.preencode(s, bump);
	}

	/// Fill pass: write this message at `s.start` (after preencode + allocate).
	void encodeInto(ref State s) const
	{
		Uint.encode(s, peers.length);
			foreach (ref x; peers)
				x.encodeInto(s);
		if (bump != 0)
			Uint.encode(s, bump);
	}

	/// Two-pass encode: size, allocate once, fill — the reference's c.encode.
	ubyte[] encode() const
	{
		State s;
		preencode(s);
		s.buffer = new ubyte[](s.end);
		encodeInto(s);
		return s.buffer;
	}

	/// Read this message at `s.start` (inline).
	static LookupReply decodeFrom(ref State s)
	{
		LookupReply m;
		immutable n_ = cast(size_t) Uint.decode(s);
			foreach (_; 0 .. n_)
			{
				PeerRecord x;
				x = PeerRecord.decodeFrom(s);
				m.peers ~= x;
			}
		if (s.start < s.end)
			m.bump = cast(uint) Uint.decode(s);
		return m;
	}

	static LookupReply decode(ubyte[] buf)
	{
		auto s = State(0, buf.length, buf);
		return decodeFrom(s);
	}
}

struct Request
{
	ushort tid;
	Address to;
	bool hasId;
	ubyte[32] id;
	bool hasToken;
	ubyte[32] token;
	bool internal;
	uint command;
	bool hasTarget;
	ubyte[32] target;
	bool hasValue;
	ubyte[] value;

	/// The flags varint (OR of the @bits present); 0 when the message has none.
	ulong flags_() const @safe pure nothrow
	{
		return (hasId ? 1UL : 0UL) | (hasToken ? 2UL : 0UL) | (internal ? 4UL : 0UL) | (hasTarget ? 8UL : 0UL) | (hasValue ? 16UL : 0UL);
	}

	/// Size pass: advance `s.end` by this message's wire size (inline, no framing).
	void preencode(ref State s) const
	{
		s.end++;
		Uint.preencode(s, flags_);
		Uint16.preencode(s, tid);
		Ipv4Address.preencode(s, to);
		if (hasId)
			Fixed!32.preencode(s, id[]);
		if (hasToken)
			Fixed!32.preencode(s, token[]);
		Uint.preencode(s, command);
		if (hasTarget)
			Fixed!32.preencode(s, target[]);
		if (hasValue)
			Buffer.preencode(s, value);
	}

	/// Fill pass: write this message at `s.start` (after preencode + allocate).
	void encodeInto(ref State s) const
	{
		s.buffer[s.start++] = 0x03;
		Uint.encode(s, flags_);
		Uint16.encode(s, tid);
		Ipv4Address.encode(s, to);
		if (hasId)
			Fixed!32.encode(s, id[]);
		if (hasToken)
			Fixed!32.encode(s, token[]);
		Uint.encode(s, command);
		if (hasTarget)
			Fixed!32.encode(s, target[]);
		if (hasValue)
			Buffer.encode(s, value);
	}

	/// Two-pass encode: size, allocate once, fill — the reference's c.encode.
	ubyte[] encode() const
	{
		State s;
		preencode(s);
		s.buffer = new ubyte[](s.end);
		encodeInto(s);
		return s.buffer;
	}

	/// Read this message at `s.start` (inline).
	static Request decodeFrom(ref State s)
	{
		Request m;
		if (s.start >= s.end || s.buffer[s.start] != 0x03)
			throw new Exception("Request: bad type byte");
		s.start++;
		immutable flags_ = Uint.decode(s);
		m.tid = cast(ushort) Uint16.decode(s);
		m.to = Ipv4Address.decode(s);
		if (flags_ & 1)
		{
			m.id[] = Fixed!32.decode(s)[0 .. 32];
			m.hasId = true;
		}
		if (flags_ & 2)
		{
			m.token[] = Fixed!32.decode(s)[0 .. 32];
			m.hasToken = true;
		}
		m.internal = (flags_ & 4) != 0;
		m.command = cast(uint) Uint.decode(s);
		if (flags_ & 8)
		{
			m.target[] = Fixed!32.decode(s)[0 .. 32];
			m.hasTarget = true;
		}
		if (flags_ & 16)
		{
			m.value = Buffer.decode(s);
			m.hasValue = true;
		}
		return m;
	}

	static Request decode(ubyte[] buf)
	{
		auto s = State(0, buf.length, buf);
		return decodeFrom(s);
	}
}

struct Reply
{
	ushort tid;
	Address to;
	bool hasId;
	ubyte[32] id;
	bool hasToken;
	ubyte[32] token;
	bool hasCloserNodes;
	Address[] closerNodes;
	uint error;
	bool hasValue;
	ubyte[] value;

	/// The flags varint (OR of the @bits present); 0 when the message has none.
	ulong flags_() const @safe pure nothrow
	{
		return (hasId ? 1UL : 0UL) | (hasToken ? 2UL : 0UL) | (hasCloserNodes ? 4UL : 0UL) | (error != 0 ? 8UL : 0UL) | (hasValue ? 16UL : 0UL);
	}

	/// Size pass: advance `s.end` by this message's wire size (inline, no framing).
	void preencode(ref State s) const
	{
		s.end++;
		Uint.preencode(s, flags_);
		Uint16.preencode(s, tid);
		Ipv4Address.preencode(s, to);
		if (hasId)
			Fixed!32.preencode(s, id[]);
		if (hasToken)
			Fixed!32.preencode(s, token[]);
		if (hasCloserNodes)
			ArrayOf!Ipv4Address.preencode(s, closerNodes);
		if (error != 0)
			Uint.preencode(s, error);
		if (hasValue)
			Buffer.preencode(s, value);
	}

	/// Fill pass: write this message at `s.start` (after preencode + allocate).
	void encodeInto(ref State s) const
	{
		s.buffer[s.start++] = 0x13;
		Uint.encode(s, flags_);
		Uint16.encode(s, tid);
		Ipv4Address.encode(s, to);
		if (hasId)
			Fixed!32.encode(s, id[]);
		if (hasToken)
			Fixed!32.encode(s, token[]);
		if (hasCloserNodes)
			ArrayOf!Ipv4Address.encode(s, closerNodes);
		if (error != 0)
			Uint.encode(s, error);
		if (hasValue)
			Buffer.encode(s, value);
	}

	/// Two-pass encode: size, allocate once, fill — the reference's c.encode.
	ubyte[] encode() const
	{
		State s;
		preencode(s);
		s.buffer = new ubyte[](s.end);
		encodeInto(s);
		return s.buffer;
	}

	/// Read this message at `s.start` (inline).
	static Reply decodeFrom(ref State s)
	{
		Reply m;
		if (s.start >= s.end || s.buffer[s.start] != 0x13)
			throw new Exception("Reply: bad type byte");
		s.start++;
		immutable flags_ = Uint.decode(s);
		m.tid = cast(ushort) Uint16.decode(s);
		m.to = Ipv4Address.decode(s);
		if (flags_ & 1)
		{
			m.id[] = Fixed!32.decode(s)[0 .. 32];
			m.hasId = true;
		}
		if (flags_ & 2)
		{
			m.token[] = Fixed!32.decode(s)[0 .. 32];
			m.hasToken = true;
		}
		if (flags_ & 4)
		{
			m.closerNodes = ArrayOf!Ipv4Address.decode(s);
			m.hasCloserNodes = true;
		}
		if (flags_ & 8)
		{
			m.error = cast(uint) Uint.decode(s);
		}
		if (flags_ & 16)
		{
			m.value = Buffer.decode(s);
			m.hasValue = true;
		}
		return m;
	}

	static Reply decode(ubyte[] buf)
	{
		auto s = State(0, buf.length, buf);
		return decodeFrom(s);
	}
}

