/**
 * The three key types libsodium does not cover, against vectors produced
 * elsewhere.
 *
 * Which keys a node generates for itself is a choice; which it can *verify* is
 * not. A peer's `PublicKey` protobuf arrives carrying whatever that peer picked,
 * and a node that cannot check a secp256k1 signature cannot talk to the peers
 * that use one — identify records, signed peer records and the Noise handshake
 * all rest on that check.
 *
 * Provenance is the point of this file. A vector this repository generates and
 * then asserts against proves only that the code agrees with itself: a key
 * format read wrongly is read wrongly at both ends, and the test passes. The
 * Ed25519, secp256k1 and ECDSA vectors below came out of **rust-libp2p**
 * (`interop/rust-peer/src/bin/vectors.rs`), so they disagree with us when we are
 * wrong. The RSA one is weaker and labelled as such.
 *
 * The PeerId assertions are the sharpest of the four checks: they depend on the
 * exact protobuf bytes, on the multihash choice (identity below 43 bytes, SHA-256
 * above — which is why ECDSA and RSA come out as `Qm…` rather than `12D3Koo…`)
 * and on base58. Getting a signature right while getting the PeerId wrong is not
 * possible by luck.
 */
module tests.crypto.keytypes_test;

import std.string : representation;

import libp2p.crypto.keys : PublicKey, KeyType;
import libp2p.core.peer_id : PeerId;
import fluent.asserts;

private ubyte[] unhex(string s)
{
	ubyte[] out_;
	for (size_t i = 0; i + 1 < s.length; i += 2)
	{
		ubyte hi = cast(ubyte)(s[i] <= '9' ? s[i] - '0' : s[i] - 'a' + 10);
		ubyte lo = cast(ubyte)(s[i + 1] <= '9' ? s[i + 1] - '0' : s[i + 1] - 'a' + 10);
		out_ ~= cast(ubyte)((hi << 4) | lo);
	}
	return out_;
}

/// One key type's evidence: the protobuf a peer would send, a message, a
/// signature over it, and the identity it resolves to.
private struct Vector
{
	string name;
	KeyType type;
	string pubkey; /// the `PublicKey` protobuf, hex
	string sig;
	string peerId;
}

private enum message = "libp2p-dlang interop vector";

// Generated by rust-libp2p 0.56.0. Not by us.
private static immutable Vector[] fromRust = [
	Vector("ed25519", KeyType.ed25519,
		"0801122088358aebf051bad8cdc42e4231345dd54881f821500d190eb7c36e4eb775248b",
		"e91915658e7da78d4595487a65c7c57cd490f2f5c13e1e22edf1b8518ccb8dfc"
		~ "198e52669ce1d4548ea0efa91c6f4b66a69438af9b8239799797fded52d7d30a",
		"12D3KooWJz4yALHXChosV49kQJi1rDPHpehB7PdZgju6RKR9A76i"),

	Vector("secp256k1", KeyType.secp256k1,
		"080212210291506cea01ce7ce894de1d9503b0ada9914280e39f0331163303a319823650b5",
		"304402202ccd8cf2389f040cb3153da2375c9a1ea8c720d6d4dcd854ffa1d38f21a83d66"
		~ "0220259ee4d8e3a24138de96cc5948d0617a7ec0b3cf10166ed1ced8eab78db61a36",
		"16Uiu2HAm5CvDzeH9RGvFLTxukPpGqSFU7hMR5LGtTu9ghyVHZ7Qg"),

	Vector("ecdsa", KeyType.ecdsa,
		"0803125b3059301306072a8648ce3d020106082a8648ce3d030107034200"
		~ "0474a1fef058c5a656044a0aa3fa15f369d241810b2ac5613f0639a8382a8bda01"
		~ "66cfe27e41ed251eea0badd40bca4817a6cfc98e53a8956024fb3ee436b7a85e",
		"30460221008452c2a166314bb86eac4412c7d75c1434307964f294804f65b51d989c687710"
		~ "022100cc3791bcfe4d346c02af9b4dacd62e56cd2540195b06b6e1604f1be7773348f9",
		"QmaGdzz8AKTxf3291Cm391TDhaukS3p9AoBVxF3VuifTZN"),
];

@("key types: a public key from rust-libp2p verifies its own signature")
unittest
{
	foreach (v; fromRust)
	{
		auto key = PublicKey.fromProtobuf(unhex(v.pubkey));
		(key.type == v.type).should.equal(true);
		key.verify(message.representation, unhex(v.sig)).should.equal(true);
	}
}

@("key types: a tampered message or signature is refused")
unittest
{
	foreach (v; fromRust)
	{
		auto key = PublicKey.fromProtobuf(unhex(v.pubkey));

		// One bit of the message.
		key.verify("libp2p-dlang interop vectoR".representation,
			unhex(v.sig)).should.equal(false);

		// One byte of the signature. A verifier that accepts this accepts
		// anything, and would have passed every other assertion here.
		auto bad = unhex(v.sig);
		bad[$ - 1] ^= 0x01;
		key.verify(message.representation, bad).should.equal(false);

		// And nothing at all.
		key.verify(message.representation, []).should.equal(false);
	}
}

@("key types: a public key from rust-libp2p yields the same PeerId")
unittest
{
	foreach (v; fromRust)
	{
		auto key = PublicKey.fromProtobuf(unhex(v.pubkey));
		PeerId.fromPublicKey(key).toBase58.should.equal(v.peerId);
	}
}

// RSA, with weaker provenance stated rather than glossed: rust-libp2p can import
// RSA keys but cannot generate them, so this key and signature come from the
// OpenSSL command line (2048-bit, PKCS#1 v1.5 over SHA-256, the SubjectPublicKeyInfo
// wrapped in libp2p's PublicKey protobuf by hand). It exercises the same code
// path as the ECDSA vector above — `d2i_PUBKEY` then `EVP_DigestVerify` — so what
// it adds is the RSA branch, not independent confirmation of the format.
private enum rsaPubkey = "080012a60230820122300d06092a864886f70d01010105000382010f00"
	~ "3082010a0282010100b6e4fdf57d19f9fb1f5e4d2451ba266a78ae2ee6866cda97fe97715d"
	~ "eeeca997014ddce88585e129755678f2128ab6ba3b290a353f7eac2828429e16ec7638c45e"
	~ "94d9104ccce443b80eda43a38ff6f48dc30b628bb9e36c6e131526d025b17aa254780d6866"
	~ "5508afba227feb942f2c78f5fcb8408b7bfdb1f80f4e4f796deb940705138460ee77c7aced"
	~ "154bb59d563a6314b2621d96a1c1e804b2b832119807c7f92405cf4478d613ace11de2dec4"
	~ "15fe4939b6c3453dce0d7786232697c78579cbb33510cdd67318940018af87ae427599a6bd"
	~ "0125740a29c0a2417b0fd353386f29c9cb09d8ee678b79a5a98f422163d23adaeb5a96e194"
	~ "873d12b83fb10203010001";
private enum rsaSig = "34455ae5295abfb794085e32c61ea1b09a18a82605c537d3f762bdd71bb1372e"
	~ "f4580870e678dc9b4bc86a6b4f8527eab005a704223ca57246c4f31aac5f306d5d77f257b1"
	~ "03be0997820d25f936077ee2c16880d05c1cf3b4f6116850dfa19823a178f0bb9985e92383"
	~ "f69c58be2fda2b4da0c8d984f411f8c73dcbe68517bd2d5fab465f51617da9c4f75935fe6f"
	~ "e660e7602115e15c807fe7a488e861ceff2acf549c077800592cc201c34f7c7ee03b5a36cc"
	~ "3dcf8d5246409a4fc44be2e6d97e7193623828a2828f3558fc65722b52e5061495f579cb6c"
	~ "3afb4a4e64eca1c9e163aa407fd8583aa08c0df4a57d7d3ea98b0d9d68e0b6a5f0b0b68aa9"
	~ "7f4d";

@("key types: an RSA public key verifies, and rejects a tampered signature")
unittest
{
	auto key = PublicKey.fromProtobuf(unhex(rsaPubkey));
	(key.type == KeyType.rsa).should.equal(true);
	key.verify(message.representation, unhex(rsaSig)).should.equal(true);

	auto bad = unhex(rsaSig);
	bad[0] ^= 0x01;
	key.verify(message.representation, bad).should.equal(false);
}

// A key whose bytes are not what its tag says must be refused, not guessed at.
@("key types: a key whose material does not match its tag is refused")
unittest
{
	// The secp256k1 point, labelled ECDSA: valid bytes, wrong parser.
	auto mislabelled = PublicKey(KeyType.ecdsa,
		unhex("0291506cea01ce7ce894de1d9503b0ada9914280e39f0331163303a319823650b5"));
	mislabelled.verify(message.representation, unhex(fromRust[1].sig)).should.equal(false);

	// And an empty key of each kind.
	foreach (t; [KeyType.rsa, KeyType.ecdsa, KeyType.secp256k1, KeyType.ed25519])
		PublicKey(t, []).verify(message.representation, unhex(fromRust[0].sig))
			.should.equal(false);
}
