/**
 * cencgen — a `.cenc` schema → D codec generator for compact-encoding, the
 * hyperdht counterpart of tools/protogen. A Pegged PEG grammar parses the schema
 * and a walker emits value-type structs with a two-pass `encode` (size, allocate,
 * fill — exactly how the reference and the hand-written codecs do it) and a
 * `decode`, composed from the byte-exact primitives in `libp2p.wire.cenc`.
 *
 * Run from the repository root: `dub run --root=tools/cencgen` reads
 * proto/hyperdht.cenc and (re)writes source/libp2p/wire/hyperdht.d. The output is
 * committed, like protogen's — pegged is a tool dependency, never the library's.
 *
 * Schema (see proto/hyperdht.cenc): `enum N { A = 0; }`, `message N { items }`.
 * Items, in wire order: `flags;` (leading varint of the @bits), `byte 0xNN;`
 * (literal), `flag name @N;` (a bit with no field), and fields
 * `[optional|trailing|array] type name [@N] [nonzero];`. Types: uint (varint),
 * uint16, fixed32, fixed64, buffer, ipv4, ipv4array, or a message (nested inline).
 */
module cencgen;

import pegged.grammar;
import std.array : join;
import std.conv : to;
import std.string : format;

mixin(grammar(`
Cenc:
    Doc         <  Def* eoi
    Def         <  EnumDef / MessageDef / ';'
    EnumDef     <  "enum" Ident '{' EnumField* '}'
    EnumField   <  Ident '=' Integer ';'
    MessageDef  <  "message" Ident '{' Item* '}'
    Item        <  Flags / Byte / Flag / Field / ';'
    Flags       <  "flags" ';'
    Byte        <  "byte" Hex ';'
    Flag        <  "flag" Ident Bit ';'
    Field       <  Label? Type Ident Bit? Mod* ';'
    Label       <  "optional" / "trailing" / "array"
    Mod         <  "nonzero"
    Bit         <  '@' Integer
    Type        <~ Ident
    Hex         <~ "0x" [0-9a-fA-F]+
    Ident       <~ [a-zA-Z_] [a-zA-Z0-9_]*
    Integer     <~ [0-9]+
    Spacing     <- (blank / Comment)*
    Comment     <- "//" (!endOfLine .)* endOfLine
`));

/// First letter up, the rest untouched (std.string's capitalize lowercases the
/// tail, which would turn `closerNodes` into `Closernodes`).
private string upFirst(string s)
{
	import std.ascii : toUpper;
	return s.length ? cast(char) toUpper(s[0]) ~ s[1 .. $] : s;
}

private bool isRule(ParseTree p, string rule)
{
	return p.name == "Cenc." ~ rule;
}

private struct Item
{
	string kind; // "flags" | "byte" | "flag" | "field"
	string label; // "" | "optional" | "trailing" | "array"
	string type;
	string name;
	string bit; // "@N" bit value as text, "" if none
	bool nonzero;
	string byteVal; // for kind "byte"
}

/// Generate the D module source for a `.cenc` schema.
string cencGen(string src, string moduleName)
{
	auto tree = Cenc(src);
	if (!tree.successful)
		throw new Exception("cencgen: parse error\n" ~ tree.toString);
	string[] messages;
	foreach (d; tree.children[0].children)
	{
		auto n = d.children.length ? d.children[0] : d;
		if (isRule(n, "MessageDef"))
			messages ~= n.children[0].matches[0];
	}
	string outp = "// GENERATED by tools/cencgen from proto/hyperdht.cenc — do not edit by hand.\n"
		~ "module " ~ moduleName ~ ";\n\n"
		~ "import libp2p.wire.cenc : State, Uint, Uint16, Fixed, Buffer, ArrayOf, Ipv4Address, Address;\n\n";
	foreach (d; tree.children[0].children)
	{
		auto n = d.children.length ? d.children[0] : d;
		if (isRule(n, "EnumDef"))
			outp ~= genEnum(n);
		else if (isRule(n, "MessageDef"))
			outp ~= genMessage(n, messages);
	}
	return outp;
}

private string genEnum(ParseTree p)
{
	string name = p.children[0].matches[0];
	string[] members;
	foreach (c; p.children[1 .. $])
		if (isRule(c, "EnumField"))
			members ~= c.children[0].matches[0] ~ " = " ~ c.children[1].matches[0];
	return "enum " ~ name ~ " : uint\n{\n\t" ~ members.join(",\n\t") ~ "\n}\n\n";
}

private Item parseItem(ParseTree it)
{
	Item x;
	if (isRule(it, "Flags"))
		x.kind = "flags";
	else if (isRule(it, "Byte"))
	{
		x.kind = "byte";
		x.byteVal = it.children[0].matches[0];
	}
	else if (isRule(it, "Flag"))
	{
		x.kind = "flag";
		x.name = it.children[0].matches[0];
		x.bit = it.children[1].children[0].matches[0];
	}
	else if (isRule(it, "Field"))
	{
		x.kind = "field";
		foreach (c; it.children)
		{
			if (isRule(c, "Label"))
				x.label = c.matches[0];
			else if (isRule(c, "Type"))
				x.type = c.matches[0];
			else if (isRule(c, "Ident"))
				x.name = c.matches[0];
			else if (isRule(c, "Bit"))
				x.bit = c.children[0].matches[0];
			else if (isRule(c, "Mod"))
				x.nonzero = true;
		}
	}
	return x;
}

private bool isMessage(string t, const string[] messages)
{
	foreach (m; messages)
		if (m == t)
			return true;
	return false;
}

// The D field type for a schema type.
private string dType(Item f, const string[] messages)
{
	string base;
	switch (f.type)
	{
	case "uint": base = "uint"; break;
	case "uint16": base = "ushort"; break;
	case "fixed32": base = "ubyte[32]"; break;
	case "fixed64": base = "ubyte[64]"; break;
	case "buffer": base = "ubyte[]"; break;
	case "ipv4": base = "Address"; break;
	case "ipv4array": base = "Address[]"; break;
	default:
		if (!isMessage(f.type, messages))
			throw new Exception("cencgen: unknown type " ~ f.type);
		base = f.type;
	}
	return f.label == "array" ? base ~ "[]" : base;
}

// Presence: an `optional` field carries `has<Name>` unless it is `nonzero`
// (presence = value != 0); `trailing` is present iff non-zero on encode.
private bool hasFlag(Item f)
{
	return f.kind == "field" && f.label == "optional" && !f.nonzero;
}

private string presentExpr(Item f)
{
	if (f.kind == "flag")
		return f.name;
	if (hasFlag(f))
		return "has" ~ upFirst(f.name);
	if (f.type == "buffer" || f.type == "ipv4array" || f.label == "array")
		return f.name ~ ".length != 0";
	return f.name ~ " != 0";
}

// preencode / encode / decode of ONE value expression `v` of type f.type.
private string preencodeOf(Item f, string v, const string[] messages)
{
	switch (f.type)
	{
	case "uint": return "Uint.preencode(s, " ~ v ~ ");";
	case "uint16": return "Uint16.preencode(s, " ~ v ~ ");";
	case "fixed32": return "Fixed!32.preencode(s, " ~ v ~ "[]);";
	case "fixed64": return "Fixed!64.preencode(s, " ~ v ~ "[]);";
	case "buffer": return "Buffer.preencode(s, " ~ v ~ ");";
	case "ipv4": return "Ipv4Address.preencode(s, " ~ v ~ ");";
	case "ipv4array": return "ArrayOf!Ipv4Address.preencode(s, " ~ v ~ ");";
	default: return v ~ ".preencode(s);";
	}
}

private string encodeOf(Item f, string v, const string[] messages)
{
	switch (f.type)
	{
	case "uint": return "Uint.encode(s, " ~ v ~ ");";
	case "uint16": return "Uint16.encode(s, " ~ v ~ ");";
	case "fixed32": return "Fixed!32.encode(s, " ~ v ~ "[]);";
	case "fixed64": return "Fixed!64.encode(s, " ~ v ~ "[]);";
	case "buffer": return "Buffer.encode(s, " ~ v ~ ");";
	case "ipv4": return "Ipv4Address.encode(s, " ~ v ~ ");";
	case "ipv4array": return "ArrayOf!Ipv4Address.encode(s, " ~ v ~ ");";
	default: return v ~ ".encodeInto(s);";
	}
}

private string decodeOf(Item f, string target, const string[] messages)
{
	switch (f.type)
	{
	case "uint": return target ~ " = cast(uint) Uint.decode(s);";
	case "uint16": return target ~ " = cast(ushort) Uint16.decode(s);";
	case "fixed32": return target ~ "[] = Fixed!32.decode(s)[0 .. 32];";
	case "fixed64": return target ~ "[] = Fixed!64.decode(s)[0 .. 64];";
	case "buffer": return target ~ " = Buffer.decode(s);";
	case "ipv4": return target ~ " = Ipv4Address.decode(s);";
	case "ipv4array": return target ~ " = ArrayOf!Ipv4Address.decode(s);";
	default: return target ~ " = " ~ f.type ~ ".decodeFrom(s);";
	}
}

private string genMessage(ParseTree p, const string[] messages)
{
	string name = p.children[0].matches[0];
	Item[] items;
	foreach (c; p.children[1 .. $])
	{
		auto it = (isRule(c, "Item") && c.children.length) ? c.children[0] : c;
		auto x = parseItem(it);
		if (x.kind.length)
			items ~= x;
	}

	// --- struct fields ---
	string decls;
	foreach (f; items)
	{
		if (f.kind == "flag")
			decls ~= "\tbool " ~ f.name ~ ";\n";
		else if (f.kind == "field")
		{
			if (hasFlag(f))
				decls ~= "\tbool has" ~ upFirst(f.name) ~ ";\n";
			decls ~= "\t" ~ dType(f, messages) ~ " " ~ f.name ~ ";\n";
		}
	}

	// --- the flags varint: OR of every @bit item's presence ---
	string flagsExpr;
	foreach (f; items)
		if (f.bit.length)
			flagsExpr ~= (flagsExpr.length ? " | " : "") ~ "(" ~ presentExpr(f) ~ " ? " ~ f.bit ~ "UL : 0UL)";
	if (!flagsExpr.length)
		flagsExpr = "0UL";

	// --- preencode / encodeInto / decodeFrom, item by item, in wire order ---
	string pre, enc, dec;
	foreach (f; items)
	{
		final switch (f.kind)
		{
		case "flags":
			pre ~= "\t\tUint.preencode(s, flags_);\n";
			enc ~= "\t\tUint.encode(s, flags_);\n";
			dec ~= "\t\timmutable flags_ = Uint.decode(s);\n";
			break;
		case "byte":
			pre ~= "\t\ts.end++;\n";
			enc ~= "\t\ts.buffer[s.start++] = " ~ f.byteVal ~ ";\n";
			dec ~= "\t\tif (s.start >= s.end || s.buffer[s.start] != " ~ f.byteVal ~ ")\n"
				~ "\t\t\tthrow new Exception(\"" ~ name ~ ": bad type byte\");\n\t\ts.start++;\n";
			break;
		case "flag":
			dec ~= "\t\tm." ~ f.name ~ " = (flags_ & " ~ f.bit ~ ") != 0;\n";
			break;
		case "field":
			string v = f.name;
			string preOne, encOne, decOne;
			if (f.label == "array")
			{
				preOne = "Uint.preencode(s, " ~ v ~ ".length);\n\t\t\tforeach (ref x; " ~ v ~ ")\n\t\t\t\t" ~ preencodeOf(f, "x", messages);
				encOne = "Uint.encode(s, " ~ v ~ ".length);\n\t\t\tforeach (ref x; " ~ v ~ ")\n\t\t\t\t" ~ encodeOf(f, "x", messages);
				decOne = "immutable n_ = cast(size_t) Uint.decode(s);\n\t\t\tforeach (_; 0 .. n_)\n\t\t\t{\n\t\t\t\t"
					~ dType(f, messages)[0 .. $ - 2] ~ " x;\n\t\t\t\t" ~ decodeOf(f, "x", messages) ~ "\n\t\t\t\tm." ~ v ~ " ~= x;\n\t\t\t}";
			}
			else
			{
				preOne = preencodeOf(f, v, messages);
				encOne = encodeOf(f, v, messages);
				decOne = decodeOf(f, "m." ~ v, messages);
			}
			if (f.label == "optional")
			{
				pre ~= "\t\tif (" ~ presentExpr(f) ~ ")\n\t\t\t" ~ preOne ~ "\n";
				enc ~= "\t\tif (" ~ presentExpr(f) ~ ")\n\t\t\t" ~ encOne ~ "\n";
				dec ~= "\t\tif (flags_ & " ~ f.bit ~ ")\n\t\t{\n\t\t\t" ~ decOne ~ "\n"
					~ (hasFlag(f) ? "\t\t\tm.has" ~ upFirst(f.name) ~ " = true;\n" : "") ~ "\t\t}\n";
			}
			else if (f.label == "trailing")
			{
				pre ~= "\t\tif (" ~ presentExpr(f) ~ ")\n\t\t\t" ~ preOne ~ "\n";
				enc ~= "\t\tif (" ~ presentExpr(f) ~ ")\n\t\t\t" ~ encOne ~ "\n";
				dec ~= "\t\tif (s.start < s.end)\n\t\t\t" ~ decOne ~ "\n";
			}
			else
			{
				pre ~= "\t\t" ~ preOne ~ "\n";
				enc ~= "\t\t" ~ encOne ~ "\n";
				dec ~= "\t\t" ~ decOne ~ "\n";
			}
			break;
		}
	}

	return "struct " ~ name ~ "\n{\n" ~ decls
		~ "\n\t/// The flags varint (OR of the @bits present); 0 when the message has none.\n"
		~ "\tulong flags_() const @safe pure nothrow\n\t{\n\t\treturn " ~ flagsExpr ~ ";\n\t}\n"
		~ "\n\t/// Size pass: advance `s.end` by this message's wire size (inline, no framing).\n"
		~ "\tvoid preencode(ref State s) const\n\t{\n" ~ pre ~ "\t}\n"
		~ "\n\t/// Fill pass: write this message at `s.start` (after preencode + allocate).\n"
		~ "\tvoid encodeInto(ref State s) const\n\t{\n" ~ enc ~ "\t}\n"
		~ "\n\t/// Two-pass encode: size, allocate once, fill — the reference's c.encode.\n"
		~ "\tubyte[] encode() const\n\t{\n\t\tState s;\n\t\tpreencode(s);\n\t\ts.buffer = new ubyte[](s.end);\n\t\tencodeInto(s);\n\t\treturn s.buffer;\n\t}\n"
		~ "\n\t/// Read this message at `s.start` (inline).\n"
		~ "\tstatic " ~ name ~ " decodeFrom(ref State s)\n\t{\n\t\t" ~ name ~ " m;\n" ~ dec ~ "\t\treturn m;\n\t}\n"
		~ "\n\tstatic " ~ name ~ " decode(ubyte[] buf)\n\t{\n\t\tauto s = State(0, buf.length, buf);\n\t\treturn decodeFrom(s);\n\t}\n"
		~ "}\n\n";
}

int main(string[] args)
{
	import std.file : readText, write, exists;
	import std.stdio : writeln, stderr;

	// Paths are relative to the repository root (dub run --root=tools/cencgen
	// chdirs into the tool), so climb back out.
	immutable schema = args.length > 1 ? args[1] : "../../proto/hyperdht.cenc";
	immutable outFile = args.length > 2 ? args[2] : "../../source/libp2p/wire/hyperdht.d";
	if (!exists(schema))
	{
		stderr.writeln("cencgen: schema not found: ", schema);
		return 1;
	}
	auto src = cencGen(readText(schema), "libp2p.wire.hyperdht");
	write(outFile, src);
	writeln("cencgen: ", schema, " -> ", outFile, " (", src.length, " bytes)");
	return 0;
}
