// Generates byte-exact vectors from the REAL compact-encoding (holepunchto,
// pinned d579287, cloned at ../../../compact-encoding). Emits a D module the
// test asserts against. The case names here must match the D test's cases.
const path = require('path')
const fs = require('fs')
const c = require(path.join(__dirname, '../../../compact-encoding'))

const cases = []
const add = (name, enc, value) => {
  cases.push({ name, hex: c.encode(enc, value).toString('hex') })
}
const buf = (arr) => Buffer.from(arr)

// uint (varint)
add('uint:0', c.uint, 0)
add('uint:1', c.uint, 1)
add('uint:0xfc', c.uint, 0xfc)
add('uint:0xfd', c.uint, 0xfd)
add('uint:0xff', c.uint, 0xff)
add('uint:0x100', c.uint, 0x100)
add('uint:0xffff', c.uint, 0xffff)
add('uint:0x10000', c.uint, 0x10000)
add('uint:0xffffffff', c.uint, 0xffffffff)
add('uint:0x100000000', c.uint, 0x100000000)
add('uint:maxsafe', c.uint, Number.MAX_SAFE_INTEGER)

// fixed-width uints
add('uint8:255', c.uint8, 255)
add('uint16:65535', c.uint16, 65535)
add('uint24:0x123456', c.uint24, 0x123456)
add('uint32:0xdeadbeef', c.uint32, 0xdeadbeef)
add('uint32be:0xdeadbeef', c.uint32be, 0xdeadbeef)
add('uint40:0x123456789a', c.uint40, 0x123456789a)
add('uint48:0x123456789abc', c.uint48, 0x123456789abc)
add('uint56:0x123456789abcde', c.uint56, 0x123456789abcde)
add('uint64:0x1fffffffffffff', c.uint64, 0x1fffffffffffff)
add('uint64be:0x1fffffffffffff', c.uint64be, 0x1fffffffffffff)

// signed (zig-zag)
add('int:0', c.int, 0)
add('int:-1', c.int, -1)
add('int:1', c.int, 1)
add('int:-2', c.int, -2)
add('int:2', c.int, 2)
add('int:100', c.int, 100)
add('int:-100', c.int, -100)
add('int:maxsafe', c.int, 2 ** 52 - 1)
add('int:minsafe', c.int, -(2 ** 52))
add('int32:-70000', c.int32, -70000)

// float
add('float32:1.5', c.float32, 1.5)
add('float64:-3.14159', c.float64, -3.14159)

// bool
add('bool:true', c.bool, true)
add('bool:false', c.bool, false)

// buffers
add('buffer:empty', c.buffer, buf([]))
add('buffer:123', c.buffer, buf([1, 2, 3]))
add('buffer:300', c.buffer, buf(Array.from({ length: 300 }, (_, i) => i & 0xff)))

// fixed
add('fixed4:1234', c.fixed(4), buf([1, 2, 3, 4]))
add('fixed32', c.fixed32, buf(Array.from({ length: 32 }, (_, i) => i)))

// strings
add('utf8:empty', c.string, '')
add('utf8:hi', c.string, 'hi')
add('utf8:multibyte', c.string, 'héllo')
add('utf8:long', c.string, 'x'.repeat(300))

// arrays
add('array-uint:empty', c.array(c.uint), [])
add('array-uint:123', c.array(c.uint), [1, 2, 3])
add('array-uint:big', c.array(c.uint), [300, 70000])
add('array-utf8', c.array(c.string), ['a', 'bb'])

// frame
add('frame-utf8:hello', c.frame(c.string), 'hello')

// ip
add('ipv4:127.0.0.1', c.ipv4, '127.0.0.1')
add('ipv4:255.255.255.255', c.ipv4, '255.255.255.255')
add('ipv6:::1', c.ipv6, '::1')
add('ipv6:2001:db8::1', c.ipv6, '2001:db8::1')
add('ipv6:fe80::1', c.ipv6, 'fe80::1')
add('ip:v4', c.ip, '127.0.0.1')
add('ip:v6', c.ip, '::1')
add('ipAddress:v4', c.ipAddress, { host: '127.0.0.1', port: 49737 })
add('ipAddress:v6', c.ipAddress, { host: '::1', port: 1 })
add('ipv4Address', c.ipv4Address, { host: '10.0.0.7', port: 8080 })
add('ipv6Address', c.ipv6Address, { host: '2001:db8::1', port: 4001 })

let out = '// GENERATED by tests/vectors/gen.js from the real compact-encoding\n'
out += '// (holepunchto/compact-encoding d579287). Do not edit by hand.\n'
out += 'module tests.cenc_vectors;\n\n'
out += 'struct CencVec { string name; string hex; }\n\n'
out += 'immutable CencVec[] cencVectors = [\n'
for (const { name, hex } of cases) {
  out += `    CencVec(${JSON.stringify(name)}, ${JSON.stringify(hex)}),\n`
}
out += '];\n'

fs.writeFileSync(path.join(__dirname, '../cenc_vectors.d'), out)
console.log('wrote ' + cases.length + ' vectors')
